CREATE TABLE accounts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT         NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    type       VARCHAR(20)    NOT NULL,
    balance    DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    currency   VARCHAR(3)     NOT NULL DEFAULT 'USD',
    created_at TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);
